---
# tasks file for amq-online
- name: Create temporary directory
  when:
    - _amqonline_state == "present"
  tempfile:
    state: directory
    suffix: amqonlineinstaller
  register: installer

- debug:
    var: installer

- name: Unarchive the installer
  when:
    - _amqonline_state == "present"
  unarchive:
    src: "{{ amqonline_install_url }}"
    dest: "{{ installer.path }}"
    remote_src: yes

- name: set "{{ _amqonline_infra_proj }}" namespace to "{{ _amqonline_state }}"
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ _amqonline_infra_proj }}"
    state: "{{ _amqonline_state }}"
  ignore_errors: true

- name: set AMQ Online Operator Group to {{ _amqonline_state }}
  k8s:
    state: "{{ _amqonline_state }}"
    definition: "{{ lookup('template', './templates/amq_online_operator_group.j2') | from_yaml }}"

- name: set AMQ Online Operator Subscription to {{ _amqonline_state }}
  k8s:
    state: "{{ _amqonline_state }}"
    definition: "{{ lookup('template', './templates/amq_online_subscription.j2') | from_yaml }}"

- name: sleep for 5 seconds
  wait_for:
    timeout: 5

- name: Apply installer examples
  when:
    - _amqonline_state == "present"
  k8s:
    state: "{{ _amqonline_state }}"
    resource_definition: 
      - "{{ installer.path }}/install/components/example-plans"
      - "{{ installer.path }}/install/components/example-roles"
      - "{{ installer.path }}/install/components/example-authservices/standard-authservice.yaml"

- name: Clean up temporary file
  file:
    state: absent
    path: "{{ installer.path }}"

