apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  labels:
    addressSpaceType: standard
    type: address-space
  name: demo-brokered-space
spec:
  type: brokered
  plan: brokered-single-broker
  authenticationService:
    name: standard-authservice
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac
subjects:
- kind: ServiceAccount
  name: address-space-controller
  namespace: amq-online-infra
---
apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: demo-brokered-space.demo-user
spec:
  username: demo-user
  authentication:
    type: password
    password: cGFzc3dvcmQ= # Base64 encode of 'password'
  authorization:
    - addresses:
        - '*'
      operations:
        - recv
        - send
    - addresses: []
      operations:
        - manage
    - addresses: []
      operations:
        - view
---
apiVersion: enmasse.io/v1beta1
kind: Address
metadata:
  name: demo-brokered-space.myqueue-brokered
spec:
  address: myqueue-brokered
  plan: standard-small-queue
  type: queue
