apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  labels:
    addressSpaceType: standard
    type: address-space
  name: demo-standard-space
spec:
  type: standard
  plan: standard-small
  authenticationService:
    name: standard-authservice
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac
subjects:
- kind: ServiceAccount
  name: address-space-controller
  namespace: amq-online-infra
---
apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: demo-standard-space.demo-user
spec:
  username: demo-user
  authentication:
    type: password
    password: cGFzc3dvcmQ= # Base64 encode of 'password'
  authorization:
    - addresses:
        - '*'
      operations:
        - recv
        - send
    - addresses: []
      operations:
        - manage
    - addresses: []
      operations:
        - view
---
kind: Address
apiVersion: enmasse.io/v1beta1
metadata:
  labels:
    addressType: topic
  name: demo-standard-space.mytopic
spec:
  address: mytopic
  type: topic
  plan: standard-small-topic
  forwarders: []
---
kind: Address
apiVersion: enmasse.io/v1beta1
metadata:
  labels:
    addressType: subscription
  name: demo-standard-space.mysub
spec:
  address: mysub
  type: subscription
  plan: standard-small-subscription
  topic: mytopic
  forwarders: []
---
apiVersion: enmasse.io/v1beta1
kind: Address
metadata:
  name: demo-standard-space.myqueue-standard
spec:
  address: myqueue-standard
  plan: standard-small-queue
  type: queue
