apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: demo-standard-federatedspace
  namespace: amqp-demo
spec:
  type: standard
  plan: standard-unlimited
  authenticationService:
    name: standard-authservice
  connectors:
  - name: remote
    endpointHosts:
    - host: messaging-1.apps.cluster-8656.8656.sandbox114.opentlc.com
      port: 443
    tls:
      caCert:
        valueFromSecret:
          name: remote-secret
          key: tls.crt
      clientCert:
        valueFromSecret:
          name: server-secret
          key: tls.crt
      clientKey:
        valueFromSecret:
          name: server-secret
          key: tls.key
    credentials:
      username:
        value: demo-user
      password:
        value: password
    addresses:
    - name: remoteQueue
      pattern: "*"
  endpoints:
  - name: messaging
    service: messaging
    expose:
      type: route
      routeServicePort: amqps
      routeTlsTermination: passthrough
      routeHost: messaging-1.apps.cluster-d524.d524.sandbox941.opentlc.com
    cert:
      provider: certBundle
      secretName : server-secret
    exports:
    - kind: ConfigMap
      name: federatedspace-cm
  - name: console
    service: console
    expose:
      type: route
      routeTlsTermination: reencrypt
      routeServicePort: https
    cert:
      provider: openshift
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbac-amq-online
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps","secrets" ]
    verbs: [ "create","get", "update", "patch" ]
#  - apiGroups: [ "" ]
#    resources: [ "configmaps" ]
#    resourceNames: [ "spring-boot-camel-amq-config-standard","spring-boot-camel-amq-config-brokered" ]
#    verbs: [ "get", "update", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-amq-online-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac-amq-online
subjects:
- kind: ServiceAccount
  name: address-space-controller
  namespace: amq-online-infra
---
apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: demo-standard-federatedspace.demo-user
  namespace: amqp-demo
spec:
  username: demo-user
  authentication:
    type: password
    password: cGFzc3dvcmQ= # Base64 encode of 'password'
  authorization:
    - addresses:
        - '*'
      operations:
        - recv
        - send
    - addresses: []
      operations:
        - manage
    - addresses: []
      operations:
        - view
---
apiVersion: enmasse.io/v1beta1
kind: Address
metadata:
  name: demo-standard-federatedspace.myqueue
spec:
  address: myqueue
  plan: standard-small-queue
  type: queue
  forwarders:
  - name: f1
    remoteAddress: remote/myqueue
    direction: out
