---
# tasks file for amq-online
- name: Create temporary directory
  when:
    - _amqonline_state == "present"
  tempfile:
    state: directory
    suffix: amqonlineinstaller
  register: installer

- name: Debug vars and parametrs
  debug:
    msg: "_amqonline_state: {{ _amqonline_state }}, _amqonline_install_url: {{ _amqonline_install_url }},_amqonline_infra_proj: {{ _amqonline_infra_proj }},installer: {{ installer }}"

- name: Unarchive the installer
  when:
    - _amqonline_state == "present"
  unarchive:
    src: "{{ _amqonline_install_url }}"
    dest: "{{ installer.path }}"
    remote_src: yes

- name: set {{ _amqonline_infra_proj }} namespace to {{ _amqonline_state }}
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ _amqonline_infra_proj }}"
    state: "{{ _amqonline_state }}"
  ignore_errors: true

- name: set AMQ Online Operator Group to {{ _amqonline_state }}
  k8s:
    state: "{{ _amqonline_state }}"
    definition: "{{ lookup('template', './templates/amq_online_operator_group.j2') | from_yaml }}"

- name: set AMQ Online Operator Subscription to {{ _amqonline_state }}
  k8s:
    state: "{{ _amqonline_state }}"
    definition: "{{ lookup('template', './templates/amq_online_subscription.j2') | from_yaml }}"

- name: Verify that the Operator Pod is running
  when:
    - _amqonline_state == "present"
  k8s_info:
    kind: Pod
    namespace: "{{ _amqonline_infra_proj }}"
    label_selectors:
      - app = enmasse
      - name = enmasse-operator
  register: operator_pod
  until: (operator_pod.resources|length>0) and (operator_pod.resources[0].status.phase == "Running")
  retries: 50
  delay: 10
  changed_when: false

- name: Apply installer example-plans
  when:
    - _amqonline_state == "present"
  k8s:
    namespace: "{{ _amqonline_infra_proj }}"
    state: "{{ _amqonline_state }}"
    src: "{{ installer.path }}/install/components/example-plans/{{ item.path }}"
  with_filetree: "{{ installer.path }}/install/components/example-plans"

- name: Apply installer example-roles
  when:
    - _amqonline_state == "present"
  k8s:
    namespace: "{{ _amqonline_infra_proj }}"
    state: "{{ _amqonline_state }}"
    src: "{{ installer.path }}/install/components/example-roles/{{ item.path }}"
  with_filetree: "{{ installer.path }}/install/components/example-roles"

- name: Apply installer example-authservices
  when:
    - _amqonline_state == "present"
  k8s:
    namespace: "{{ _amqonline_infra_proj }}"
    state: "{{ _amqonline_state }}"
    src: "{{ installer.path }}/install/components/example-authservices/standard-authservice.yaml"

- name: Clean up temporary file
  when:
    - _amqonline_state == "present"
  file:
    state: absent
    path: "{{ installer.path }}"
